name: iOS CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Build and Sign App
      run: |
        xcodebuild archive \
          -project CounterApp.xcodeproj \
          -scheme CounterApp \
          -archivePath build/CounterApp.xcarchive \
          -configuration Debug \
          -destination generic/platform=iOS \
          -allowProvisioningUpdates \
          DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }}
        xcodebuild -exportArchive \
          -archivePath build/CounterApp.xcarchive \
          -exportPath build/ \
          -exportOptionsPlist exportOptions.plist

    - name: Upload .ipa artifact
      uses: actions/upload-artifact@v4
      with:
        name: counter-app-build
        path: build/CounterApp.ipa